### ISSUE TITLE
Error exporting to jpg

### ISSUE THREAD

**Issue by emal1221** [giacmir/Inkscape-JPEG-export-extension#17]
Hi! I just downloaded your plugin and ImageMagick and followed all of the instructions so I'm pretty sure I did it right. When I'm ready to export the picture to jpg, I push the "Apply" button and I get this error message, "Traceback (most recent call last):

  File "jpegexport.py", line 29, in <module>

    inkex.localize()

AttributeError: 'module' object has no attribute 'localize'"

Could you tell me how to fix this? Thanks!

**Comment by Moini** [comment]
Please use Inkscape 0.91 or higher. The inkex.localize() function was introduced with that version.

**Comment by giacmir** [comment]
Alternatively, since it seems you are using an older version of Inkscape, you can try to use an older version of this plugin. 7e2ff67  for instance.

Obviously that version will be missing of the many improvements added in the meantime.

Upgrading Inskcape, as suggested by @Moini, is the best thing to do. If you are unable to do that try this other way.

**Comment by emal1221** [comment]
Ok, so I just updated to the newest version and added the extension but now when I roll over export I don't see the jpg option. Thoughts??? Thanks for the help!

**Comment by Moini** [comment]
Oh :-/ 

Just a couple of ideas:

1. Look into the file extensions.log that you will find in the directory indicated at Edit -> Preferences -> System: User config. It may give an indication as to why the extension couldn't be loaded. If you cannot figure it out, you can copy-paste the corresponding section of the file here, or attach the whole file. Also: make sure that the extension you downloaded is not an html file on the inside (some people accidentally save the page, instead of downloading the zip and copying the .py and .inx files into the correct directory).

2. There was a known issue with an uninstaller. Try if uninstalling the 0.92.1 version *completely* (preserving your user config directory, but deleting everything else) and reinstalling fixes the issue. Also make sure that you install the Python that comes with Inkscape, if you're on Windows.

**Comment by emal1221** [comment]
I did #1 and under user configuration all it says is C:\Users\Emma Lockwood\AppData\Roaming\inkscape

**Comment by Moini** [comment]
Go to that directory and open the file extension-errors.log (sorry, wrong file name in previous post).

**Comment by emal1221** [comment]
Got that to work but now it say "Please indicate a directory other than your system's base directory." but I don't see where to do that.

**Comment by Moini** [comment]
Where the file name needs to be entered, please indicate a full path to the file.

**Comment by Moini** [comment]
(btw. what was in the error log?)

**Comment by emal1221** [comment]
What does that mean?

**Comment by Moini** [comment]
Enter something like:
C:\Users\MyName\Documents\blah.jpg

**Comment by emal1221** [comment]
Got it! Thanks!!!w
